name: integration tests

on:
  push:
    branches:
      - 'feature/TRA-4197_PCAP_tests'
  # pull_request:
  #   branches:
  #     - 'main'
  # push:
  #   branches:
  #     - 'develop'

concurrency:
  group: mizu-integration-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install libpcap-dev
        run: sudo apt-get install -y libpcap-dev

      - name: Setup integration test
        run: source ./integrationTests/setup.sh

      - name: Test
        run: make integration-test

      # - name: Slack notification on failure
      #   uses: ravsamhq/notify-slack-action@v1
      #   if: always()
      #   with:
      #     status: ${{ job.status }}
      #     notification_title: 'Mizu {workflow} has {status_message}'
      #     message_format: '{emoji} *{workflow}* {status_message} during <{run_url}|run>, after commit: <{commit_url}|{commit_sha}>'
      #     footer: 'Linked Repo <{repo_url}|{repo}>'
      #     notify_when: 'failure'
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
